### ISSUE TITLE
cant install gauge plugin for visual studio 2017

### ISSUE THREAD

**Issue by tzuravner** [getgauge/gauge-visualstudio#182]
### Expected behavior
after installing the gauge plugin from nuGet and the gauge installation with the c# runner
excpecting to see gauge supported feature in visual studio like gauge template, runing\debug using the test tab and regocnize the .spec file with its formar

### Actual behavior
nothing from the above happin as vs 2017 not regocnizing the plugin

### Steps to reproduce
1.installing from Nuget
2.also downloading the .vsix file "Gauge.visualstudio.visx"

### Version Information

VisualStudio Version and Edition  :-  2017 community
Gauge VisualStudio Plugin Version :-

```
Gauge version: 0.8.1

Plugins
-------
csharp (0.10.0)
html-report (3.1.0)
```

**Comment by sguptatw** [comment]
Unable to find the Gauge plugin in Tools -> "Extensions and Updates" search for VS2017

**Comment by sriv** [comment]
Gauge Visual Studio plugin is not (yet) supported with VS 2017. This will involve some development effort.

**Comment by fruityoat** [comment]
Any plan for this to happen? The longer it is put off, the more outdated VS 2015 gets ;)

**Comment by zabil** [comment]
@fruityoat we are exploring two options here.

1. Support for C# in  [VS Code](https://code.visualstudio.com/) using our [VS Code plugin](https://github.com/getgauge/gauge-vscode) 
2. Support 2017 after Visual Studio team makes a stable release of their [language server client](https://marketplace.visualstudio.com/items?itemName=vsext.LanguageServerClientPreview)

We'll start working on option 1. soon are you ok using Visual Studio Code instead of VS 2017? are there any specific features you are looking for in 2017 that's not there in Visual Studio Code?

**Comment by brandon-jimmyfitz** [comment]
@zabil Has there been any progress or updated plans for option 1 above (C# with VS Code)?

**Comment by zabil** [comment]
@brandon-jimmyfitz Yes. We decided on option 1) i.e  Support for C# and .NET core, we'll be making a release should be out in the month of April.

**Comment by simgar** [comment]
That's disappointing.  VSCode is a great code editor but it's not an IDE: it doesn't support UI work and it only supports .NET Core so it's only good for new stuff, not legacy.

**Comment by tzuravner** [comment]
im still missing the ability to work with vs2017
im keeping the vs2015 installed only because of gauge

**Comment by simmonskeith** [comment]
i would also like to see the extension for vs2017.  i also only keep vs2015 around just for gauge work.

**Comment by sriv** [comment]
Hi everyone, thanks for the feedback.

Just wanted to share an update. As @zabil [stated]  we plan to release C# support for VSCode based on .Net Core. 

However, since we've been getting a lot of interest in Gauge plugin for VS2017, this is something we will work on before that. The aim is to bring whatever is supported in VS2015 to VS2017 first, and later improve on it.

All help is appreciated. If you are interested in contributing please do reach out here, or in the [gitter chat](https://gitter.im/getgauge/chat). It would help us a lot even if some of you signed up to test the nightly versions! Thank you for your support!

**Comment by sriv** [comment]
Hi all, an update. I pushed out some changes and there is a [nightly version](https://bintray.com/gauge/Gauge.VisualStudio/Nightly/_latestVersion) of Gauge-Visualstudio available.

Please feel free to try and leave any feedback here. Note that there is no new VS-2017 feature introduced in this yet.

**Comment by sguptatw** [comment]
**Test cases**
IDE Features available on VS2015 should also be available on VS2017

- [ ] Install seamlessly - - Should be able to install seamlessly - https://github.com/getgauge/gauge-visualstudio/issues/238 for Details
- [ ] Create projects - Should be able to create new projects using templates - https://github.com/getgauge-contrib/gauge-visualstudio-templates/issues/1
- [x] Autocomplete
- [x] Goto definition
- [x] Refactor steps
- [x] Find Usages
- [x] Navigation
- [ ] Test Explorer - Should be able to execute specs from Test Explorer - https://github.com/getgauge/gauge-visualstudio/issues/235https://github.com/getgauge/gauge-visualstudio/issues/235

Once the Run functionality is fixed Run, Debug and Run in parallel to be tested.

**Comment by r0ckburn** [comment]
Has this issue been resolved?

**Comment by sriv** [comment]
I believe some of us are experiencing #235 in their machine. I am unable to replicate this. I need to investigate on a fresh machine.

If test explorer does not work then I don't think we can call this done :(

If anybody is interested in helping out, the [nightly version](https://bintray.com/gauge/Gauge.VisualStudio/Nightly/_latestVersion) should include the support for vs2017.

**Comment by r0ckburn** [comment]
@sriv Thank you for the response. The nightly version does not display the gauge plugin when creating a new test project or new spec or concept item. I am limited to creating a test solution from the command-line. Do you have any suggestions of how to use the nightly version and create a new project or spec item from the command line?

**Comment by sguptatw** [comment]
Tracking creating of projects using templates separately - getgauge-contrib/gauge-visualstudio-templates#1
